### ISSUE TITLE
Error upon startup

### ISSUE THREAD

**Issue by MF-Bra** [iproptech/Poly#3]
Hi,

Just set up this node server and I'm getting this error.

Thanks for your support.

2022-12-30 10:14:46,877 NodeServer polyinterface      INFO     sensibo_poly:start: Sensibo NodeServer Starting
2022-12-30 10:14:46,878 NodeServer polyinterface      INFO     polyinterface:saveCustomParams: Sending customParams to Polyglot.
2022-12-30 10:14:46,878 NodeServer polyinterface      INFO     sensibo_poly:discover: Scanning mode in process
2022-12-30 10:14:48,763 NodeServer polyinterface      INFO     sensibo_poly:discover: ifw8kSPC
2022-12-30 10:14:48,765 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - CLITEMP: 25.2, uom: 56
2022-12-30 10:14:48,767 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - CLIHUM: 76.8, uom: 51
2022-12-30 10:14:48,769 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - CLIMD: 2, uom: 67
2022-12-30 10:14:48,770 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - GV0: 1, uom: 2
2022-12-30 10:14:48,771 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - GV1: 49, uom: 57
2022-12-30 10:14:48,772 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - GV2: 25, uom: 25
2022-12-30 10:14:48,773 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - CLIFRS: 2, uom: 25
2022-12-30 10:14:48,774 NodeServer polyinterface      INFO     polyinterface:addNode: Adding node Ar Escritorio(ifw8kspc)
2022-12-30 10:14:48,775 NodeServer polyinterface      INFO     sensibo_poly:discover: D654Vfjk
2022-12-30 10:14:48,777 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver d654vfjk - CLITEMP: 24.3, uom: 56
2022-12-30 10:14:48,777 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver d654vfjk - CLIHUM: 82, uom: 51
2022-12-30 10:14:48,778 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver d654vfjk - CLIMD: 6, uom: 67
2022-12-30 10:14:48,779 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver d654vfjk - GV0: 1, uom: 2
2022-12-30 10:14:48,780 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver d654vfjk - GV1: 80, uom: 57
2022-12-30 10:14:48,795 NodeServer polyinterface      ERROR    polyinterface:write: Exception in thread NodeServer:
Traceback (most recent call last):
  File "./sensibo_poly.py", line 60, in discover
    self.addNode(SensiboNode(self, self.address, dv['id'].lower(), dv, sensibo))
  File "/home/pi/.polyglot/nodeservers/Sensibo/sensibo_node.py", line 18, in __init__
    self._update(data)
  File "/home/pi/.polyglot/nodeservers/Sensibo/sensibo_node.py", line 32, in _update
    self.setDriver('GV2', data['acState']['targetTemperature'])
KeyError: 'targetTemperature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./sensibo_poly.py", line 24, in start
    self.check_params()
  File "./sensibo_poly.py", line 83, in check_params
    self.discover()
  File "./sensibo_poly.py", line 62, in discover
    except(err):
NameError: name 'err' is not defined
2022-12-30 10:15:46,852 Controller polyinterface      INFO     sensibo_poly:shortPoll: Skipping shortPoll() - NodeServer in scanning mode

**Comment by iproptech** [comment]
Hi, how are you?

What are the names set for the devices in the Sensibo app?

Thanks

Eduardo

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: MF-Bra ***@***.***>
Enviado: Friday, December 30, 2022 10:23:10 AM
Para: iproptech/Poly ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [iproptech/Poly] Error upon startup (Issue #3)


Hi,

Just set up this node server and I'm getting this error.

Thanks for your support.

2022-12-30 10:14:46,877 NodeServer polyinterface INFO sensibo_poly:start: Sensibo NodeServer Starting
2022-12-30 10:14:46,878 NodeServer polyinterface INFO polyinterface:saveCustomParams: Sending customParams to Polyglot.
2022-12-30 10:14:46,878 NodeServer polyinterface INFO sensibo_poly:discover: Scanning mode in process
2022-12-30 10:14:48,763 NodeServer polyinterface INFO sensibo_poly:discover: ifw8kSPC
2022-12-30 10:14:48,765 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver ifw8kspc - CLITEMP: 25.2, uom: 56
2022-12-30 10:14:48,767 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver ifw8kspc - CLIHUM: 76.8, uom: 51
2022-12-30 10:14:48,769 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver ifw8kspc - CLIMD: 2, uom: 67
2022-12-30 10:14:48,770 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver ifw8kspc - GV0: 1, uom: 2
2022-12-30 10:14:48,771 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver ifw8kspc - GV1: 49, uom: 57
2022-12-30 10:14:48,772 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver ifw8kspc - GV2: 25, uom: 25
2022-12-30 10:14:48,773 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver ifw8kspc - CLIFRS: 2, uom: 25
2022-12-30 10:14:48,774 NodeServer polyinterface INFO polyinterface:addNode: Adding node Ar Escritorio(ifw8kspc)
2022-12-30 10:14:48,775 NodeServer polyinterface INFO sensibo_poly:discover: D654Vfjk
2022-12-30 10:14:48,777 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver d654vfjk - CLITEMP: 24.3, uom: 56
2022-12-30 10:14:48,777 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver d654vfjk - CLIHUM: 82, uom: 51
2022-12-30 10:14:48,778 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver d654vfjk - CLIMD: 6, uom: 67
2022-12-30 10:14:48,779 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver d654vfjk - GV0: 1, uom: 2
2022-12-30 10:14:48,780 NodeServer polyinterface INFO polyinterface:reportDriver: Updating Driver d654vfjk - GV1: 80, uom: 57
2022-12-30 10:14:48,795 NodeServer polyinterface ERROR polyinterface:write: Exception in thread NodeServer:
Traceback (most recent call last):
File "./sensibo_poly.py", line 60, in discover
self.addNode(SensiboNode(self, self.address, dv['id'].lower(), dv, sensibo))
File "/home/pi/.polyglot/nodeservers/Sensibo/sensibo_node.py", line 18, in init
self._update(data)
File "/home/pi/.polyglot/nodeservers/Sensibo/sensibo_node.py", line 32, in _update
self.setDriver('GV2', data['acState']['targetTemperature'])
KeyError: 'targetTemperature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "./sensibo_poly.py", line 24, in start
self.check_params()
File "./sensibo_poly.py", line 83, in check_params
self.discover()
File "./sensibo_poly.py", line 62, in discover
except(err):
NameError: name 'err' is not defined
2022-12-30 10:15:46,852 Controller polyinterface INFO sensibo_poly:shortPoll: Skipping shortPoll() - NodeServer in scanning mode

**Comment by MF-Bra** [comment]
Hi,

Their names are "AR Sala" , "AR Suite",  and so on... 5 devices, all of them starting with "AR" and them a space and specific names.

I have also Sensibo Homebridge working well with these names. Just for your information

**Comment by iproptech** [comment]
Send me your phone number so I can try to help you better, pls.

Thanks

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: MF-Bra ***@***.***>
Enviado: Friday, December 30, 2022 11:50:40 AM
Para: iproptech/Poly ***@***.***>
Cc: Eduardo Ventura ***@***.***>; Comment ***@***.***>
Assunto: Re: [iproptech/Poly] Error upon startup (Issue #3)


Hi,

Their names are "AR Sala" , "AR Suite", and so on... 5 devices, all of them starting with "AR" and them a space and specific names.

I have also Sensibo Homebridge working well with these names. Just for your information

**Comment by MF-Bra** [comment]
please send me a DM to 
quiabos_travessa0b@icloud.com 
to avoid posting private number here.  
I'll delete this email as soon we start talking. thanks !

**Comment by iproptech** [comment]
Me liga aqui +5511996186274

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: MF-Bra ***@***.***>
Enviado: Friday, December 30, 2022 3:50:19 PM
Para: iproptech/Poly ***@***.***>
Cc: Eduardo Ventura ***@***.***>; Comment ***@***.***>
Assunto: Re: [iproptech/Poly] Error upon startup (Issue #3)


please send me a DM to
***@***.******@***.***>
to avoid posting private number here.
I'll delete this email as soon we start talking. thanks !

**Comment by MF-Bra** [comment]
After changing the device names (replacing spaces for _ ) I'm getting this.

2022-12-30 20:14:06,020 NodeServer polyinterface      INFO     sensibo_poly:start: Sensibo NodeServer Starting
2022-12-30 20:14:06,021 NodeServer polyinterface      INFO     polyinterface:removeNotice: Sending removenotice to Polyglot for index {'key': '0'}
2022-12-30 20:14:06,022 NodeServer polyinterface      INFO     polyinterface:saveCustomParams: Sending customParams to Polyglot.
2022-12-30 20:14:06,022 NodeServer polyinterface      INFO     sensibo_poly:discover: Scanning mode in process
2022-12-30 20:14:08,474 NodeServer polyinterface      INFO     sensibo_poly:discover: ifw8kSPC
2022-12-30 20:14:08,476 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - CLITEMP: 25.5, uom: 56
2022-12-30 20:14:08,477 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - CLIHUM: 74.6, uom: 51
2022-12-30 20:14:08,478 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - CLIMD: 2, uom: 67
2022-12-30 20:14:08,480 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - GV0: 1, uom: 2
2022-12-30 20:14:08,481 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - GV1: 31, uom: 57
2022-12-30 20:14:08,482 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - GV2: 25, uom: 25
2022-12-30 20:14:08,483 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver ifw8kspc - CLIFRS: 2, uom: 25
2022-12-30 20:14:08,484 NodeServer polyinterface      INFO     polyinterface:addNode: Adding node Ar_Escritorio(ifw8kspc)
2022-12-30 20:14:08,485 NodeServer polyinterface      INFO     sensibo_poly:discover: D654Vfjk
2022-12-30 20:14:08,487 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver d654vfjk - CLITEMP: 24.5, uom: 56
2022-12-30 20:14:08,492 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver d654vfjk - CLIHUM: 82.6, uom: 51
2022-12-30 20:14:08,494 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver d654vfjk - CLIMD: 6, uom: 67
2022-12-30 20:14:08,495 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver d654vfjk - GV0: 1, uom: 2
2022-12-30 20:14:08,497 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver d654vfjk - GV1: 29, uom: 57
2022-12-30 20:14:08,509 NodeServer polyinterface      ERROR    polyinterface:write: Exception in thread NodeServer:
Traceback (most recent call last):
  File "./sensibo_poly.py", line 60, in discover
    self.addNode(SensiboNode(self, self.address, dv['id'].lower(), dv, sensibo))
  File "/home/pi/.polyglot/nodeservers/Sensibo/sensibo_node.py", line 18, in __init__
    self._update(data)
  File "/home/pi/.polyglot/nodeservers/Sensibo/sensibo_node.py", line 32, in _update
    self.setDriver('GV2', data['acState']['targetTemperature'])
KeyError: 'targetTemperature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./sensibo_poly.py", line 24, in start
    self.check_params()
  File "./sensibo_poly.py", line 83, in check_params
    self.discover()
  File "./sensibo_poly.py", line 62, in discover
    except(err):
NameError: name 'err' is not defined

**Comment by MF-Bra** [comment]
Just to inform that I managed to make it work.
After digging into the logs I noticed the error was related with target temperature... like bellow

self.setDriver('GV2', data['acState']['targetTemperature'])
KeyError: 'targetTemperature'

looking into the Sensibo APP I noticed that the devices where this error was presented was the ones with the last status equal to FAN or HEAT. After adjusting all of them to COOL. The discovery was finished. I'll follow up and post here if something new happens.

Thanks !

**Comment by iproptech** [comment]
Thanks for the update!!!

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: MF-Bra ***@***.***>
Enviado: Saturday, December 31, 2022 5:41:24 PM
Para: iproptech/Poly ***@***.***>
Cc: Eduardo Ventura ***@***.***>; Comment ***@***.***>
Assunto: Re: [iproptech/Poly] Error upon startup (Issue #3)


Just to inform that I managed to make it work.
After digging into the logs I noticed the error was related with target temperature... like bellow

self.setDriver('GV2', data['acState']['targetTemperature'])
KeyError: 'targetTemperature'

looking into the Sensibo APP I noticed that the devices where this error was presented was the ones with the last status equal to FAN or HEAT. After adjusting all of them to COOL. The discovery was finished. I'll follow up and post here if something new happens.

Thanks !

**Comment by MF-Bra** [comment]
New update. ...

I Have the Anti-Mold function enabled and noticed every time the node send a shutdown it hangs with a similar error as previously.  If I turn on anti-mold I can reproduce it immediately.

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 852, in _parseInput
    self.shortPoll()
  File "./sensibo_poly.py", line 35, in shortPoll
    self.nodes[node].update(devices)
  File "/home/pi/.polyglot/nodeservers/Sensibo/sensibo_node.py", line 23, in update
    self._update(dv)
  File "/home/pi/.polyglot/nodeservers/Sensibo/sensibo_node.py", line 32, in _update
    self.setDriver('GV2', data['acState']['targetTemperature'])
KeyError: 'targetTemperature'

Thanks again.

**Comment by MF-Bra** [comment]
Hi,  I've noticed the same errors occurring when the "mode" isn't defined to cool. So var I've confirmed that fan and heat make the nodeserver to present the error and stop working. I understand it may be not in your intention to address it, so I kindly ask you if there is any command line I can use to restart it, so I can parse the log and restart the nodeserver.  Thanks in advance.
